remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Django Template Variables Documentation
description: Documentation of Django template variables and their usage
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
